const CHANGE_SINGER_LIST = 'singers/CHANGE_SINGER_LIST'
const CHANGE_PAGE_COUNT = 'singers/CHANGE_PAGE_COUNT'
const CHANGE_ENTER_LOADING = 'singers/CHANGE_ENTER_LOADING'
const CHANGE_PULLUP_LOADING = 'singers/CHANGE_PULLUP_LOADING'
const CHANGE_PULLDOWN_LOADING = 'singers/CHANGE_PULLDOWN_LOADING'
const CHANGE_AB = 'singers/CHANGE_AB'
const CHANGE_CATEGORY = 'singers/CHANGE_CATEGORY'
export {
    CHANGE_ENTER_LOADING,
    CHANGE_PAGE_COUNT,
    CHANGE_PULLDOWN_LOADING,
    CHANGE_PULLUP_LOADING,
    CHANGE_SINGER_LIST,
    CHANGE_AB,
    CHANGE_CATEGORY,
}
