const SET_HOT_KEYWRODS = 'search/SET_HOT_KEYWRODS'
const SET_SUGGEST_LIST = 'search/SET_SUGGEST_LIST'
const SET_RESULT_SONGS_LIST = 'search/SET_RESULT_SONGS_LIST'
const SET_ENTER_LOADING = 'search/SET_ENTER_LOADING'

export {
  SET_ENTER_LOADING,
  SET_HOT_KEYWRODS,
  SET_RESULT_SONGS_LIST,
  SET_SUGGEST_LIST,
}
