const SET_CURRENT_SONG = 'player/SET_CURRENT_SONG'
const SET_FULL_SCREEN = 'player/SET_FULL_SCREEN'
const SET_PLAYING_STATE = 'player/SET_PLAYING_STATE'
const SET_SEQUENCE_PALYLIST = 'player/SET_SEQUENCE_PALYLIST'
const SET_PLAYLIST = 'player/SET_PLAYLIST'
const SET_PLAY_MODE = 'player/SET_PLAY_MODE'
const SET_CURRENT_INDEX = 'player/SET_CURRENT_INDEX'
const SET_SHOW_PLAYLIST = 'player/SET_SHOW_PLAYLIST'
const DELETE_SONG = 'player/DELETE_SONG'
const INSTERT_SONG = 'player/INSTERT_SONG'

export {
  SET_CURRENT_INDEX,
  SET_CURRENT_SONG,
  SET_FULL_SCREEN,
  SET_PLAYING_STATE,
  SET_PLAYLIST,
  SET_PLAY_MODE,
  SET_SEQUENCE_PALYLIST,
  SET_SHOW_PLAYLIST,
  DELETE_SONG,
  INSTERT_SONG
}
