const CHANGE_ATRIST = 'singerInfo/CHANGE_ATRIST'
const CHANGE_SONGS_OF_ARTIST = 'singerInfo/CHANGE_SONGS_OF_ARTIST'
const CHANGE_ENTER_LOADING = 'singerInfo/CHANGE_ENTER_LOADING'

export { CHANGE_ATRIST, CHANGE_ENTER_LOADING, CHANGE_SONGS_OF_ARTIST }
